language: java
jdk:
 - oraclejdk8
node_js: 
 - '12'

dist: trusty

before_install:
 - cd front-end
 - npm install -g @angular/cli

script:
 - cd ..
 - cd demo
 - mvn package -DskipTests
 - cd ..
 - cd front-end
 
deploy:
 provider: heroku
 api-key:
   secure: $HEROKU_API_KEY
 app: pets-api-mongodb
