language: java
jdk:
 - oraclejdk8
node_js: 12.11.1

dist: trusty

env:
 global:
  - ANGULAR_HOME=front-end

before_install:
 - nvm install stable
 - nvm use stable
 - if [[ "npm -v" != 6* ]] ; then npm i -g npm@6 ; fi

install:
 - npm install -g @angular/cli@1.0.0

before_deploy:
 - cd ..
 - cd front-end

script:
 - cd demo
 - mvn package -DskipTests

deploy:
  provider: heroku
  api-key:
    secure: $HEROKU_API_KEY
  app: pets-api-mongodb
