language: java
jdk:
 - oraclejdk8

dist: trusty
 
script: ant build
#before_install:
# - cd java

install:
 - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
 - mvn test

deploy:
  provider: heroku
  api-key:
    secure: $HEROKU_API_KEY
  app: demo
