language: java
jdk:
 - oraclejdk8
node_js: 
 - '12'

dist: trusty

before_install:
 - cd front-end
 - npm install -g @angular/cli

install:
 - npm install
 
script:
 - cd ..
 - cd demo
 - mvn package -DskipTests

after_script:
 - cd ..
 - cd front-end
 - chmod +x publish-gh-pages.sh && ./publish-gh-pages.sh
 - cd ..

deploy:
  provider: heroku
  api-key:
    secure: $HEROKU_API_KEY
  app: pets-api-mongodb
