language: java
jdk:
 - oraclejdk8
node_js: 12.11.1

dist: trusty

env:
 global:
  - ANGULAR_HOME=front-end

before_install:
 - nvm install stable
 - nvm use stable
 - if [[ "npm -v" != 6* ]] ; then npm i -g npm@6 ; fi

install:
 - npm --prefix front-end run install-travis
 - npm install -g @angular/cli@1.0.0
 
 script:
 - cd demo
 - mvn package -DskipTests

before_deploy:
 - cd ..
 - npm --prefix front-end run build-travis
 - cp -r front-end/dist/* demo/src/main/resources/static
 - pwd

deploy:
  provider: heroku
  api-key:
    secure: $HEROKU_API_KEY
  app: pets-api-mongodb
