language: java
jdk:
 - oraclejdk8

dist: trusty
 
#script: ant build
#before_install:
# - cd java



script:
 - cd demo
 - mvn package -DskipTests

deploy:
  provider: heroku
  api-key:
    secure: $HEROKU_API_KEY
  app: pets-api-mongodb
